server:
  port: 8080
  error:
    include:
      message: true

spring:
  application:
    name: rangiffler-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

grpc:
  client:
    grpcCurrencyClient:
      address: 'static://localhost:9009'
      negotiationType: PLAINTEXT
    grpcGeoClient:
      address: 'static://localhost:9010'
      negotiationType: PLAINTEXT

rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'

