server:
  port: 9005
  error:
    include:
      message: true

grpc:
  server:
    port: 9006
    max-inbound-message-size: 10485760 # 10 MB

spring:
  application:
    name: rangiffler-photo
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: postgres
    password: secret
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/photo'
  jpa:
    hibernate:
      ddl-auto: validate
grpc:
  client:
    grpcUserdataClient:
      address: 'static://localhost:9002'
      negotiationType: PLAINTEXT
    grpcGeoClient:
      address: 'static://localhost:9004'
      negotiationType: PLAINTEXT

---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    url: 'jdbc:postgresql://all-db:5432/photo'
  jpa:
    hibernate:
      ddl-auto: validate
grpc:
  client:
    grpcUserdataClient:
      address: 'static://userdata:9002'
      negotiationType: PLAINTEXT
    grpcGeoClient:
      address: 'static://geo:9004'
      negotiationType: PLAINTEXT
---
