server:
  port: 9000
  servlet:
    session:
      cookie:
        http-only: false
        secure: false

spring:
  application:
    name: rangiffler-auth
  mvc:
    log-request-details: true
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: postgres
    password: secret
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/auth'
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: '127.0.0.1'
    port: 5672
    username: 'guest'
    password: 'guest'
rangiffler-front:
  base-uri: 'http://127.0.0.1'
rangiffler-auth:
  base-uri: 'http://127.0.0.1:9000'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    url: 'jdbc:postgresql://all-db:5432/auth'
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: 'rabbit-mq'
    port: 5672
    username: 'guest'
    password: 'guest'
rangiffler-front:
  base-uri: 'http://127.0.0.1'
rangiffler-auth:
  base-uri: 'http://auth:9000'
---
